import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { AppCommonModule } from 'src/app/app-common/app-common.module';
import { InventoryService } from '../inventory.service';
import { of } from 'rxjs';

@Component({
  selector: 'app-inventory-preview',
  standalone: true,
  imports: [AppCommonModule, CommonModule],
  templateUrl: './inventory-preview.component.html',
  styleUrl: './inventory-preview.component.scss'
})
export class InventoryPreviewComponent implements OnInit {



  sample_object: any = {
    "24": {
      "23": {
        "34": [
          {
            "id": 273,
            "ingredients": [
              "[",
              "'",
              "R",
              "o",
              "m",
              "a",
              "i",
              "n",
              "e",
              " ",
              "l",
              "e",
              "t",
              "t",
              "u",
              "c",
              "e",
              "'",
              ",",
              " ",
              "'",
              "C",
              "r",
              "o",
              "u",
              "t",
              "o",
              "n",
              "s",
              "'",
              ",",
              " ",
              "'",
              "P",
              "a",
              "r",
              "m",
              "e",
              "s",
              "a",
              "n",
              " ",
              "c",
              "h",
              "e",
              "e",
              "s",
              "e",
              "'",
              ",",
              " ",
              "'",
              "C",
              "a",
              "e",
              "s",
              "a",
              "r",
              " ",
              "d",
              "r",
              "e",
              "s",
              "s",
              "i",
              "n",
              "g",
              "'",
              "]"
            ],
            "category": {
              "id": 24,
              "name": "Salad",
              "created_at": "2024-07-13T11:27:55.054329Z",
              "vendor": 32
            },
            "sub_category": {
              "id": 23,
              "name": "nan",
              "created_at": "2024-07-18T18:50:01.813599Z",
              "category": 24,
              "vendor": null
            },
            "sub_sub_category": {
              "id": 34,
              "name": "",
              "created_at": "2024-07-18T18:50:02.009765Z",
              "subcategory": 23,
              "vendor": null
            },
            "menu_item": "Vegetarian",
            "item_type": "Vegetarian",
            "description": "Classic Caesar salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.",
            "price": null,
            "s_price": "0.00",
            "m_price": "0.00",
            "l_price": "0.00",
            "xl_price": "0.00",
            "size_type": "nan",
            "estimate_time": 20,
            "spiciness": "Medium",
            "calories": "200.00",
            "stock": 20,
            "in_stock": true,
            "chef_special": true,
            "upcoming": true,
            "rating": "4.40",
            "created_at": "2024-07-18T18:50:02.073673Z",
            "vendor": 30
          }
        ]
      }
    }
  }

  obj: any = {
    "success": true,
    "message": "Successfully fetched inventory details for all branches",
    "response": [
      {
        "id": 257,
        "ingredients": [
          "[",
          "'",
          "F",
          "l",
          "o",
          "u",
          "r",
          "'",
          ",",
          " ",
          "'",
          "T",
          "o",
          "m",
          "a",
          "t",
          "o",
          " ",
          "s",
          "a",
          "u",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "M",
          "o",
          "z",
          "z",
          "a",
          "r",
          "e",
          "l",
          "l",
          "a",
          " ",
          "c",
          "h",
          "e",
          "e",
          "s",
          "e",
          "'",
          ",",
          " ",
          "'",
          "B",
          "a",
          "s",
          "i",
          "l",
          "'",
          "]"
        ],
        "category": {
          "id": 42,
          "name": "Food",
          "created_at": "2024-07-13T11:27:33.935956Z",
          "vendor": 32
        },
        "sub_category": {
          "id": 30,
          "name": "Main Course",
          "created_at": "2024-07-13T12:07:46.768169Z",
          "category": 22,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 41,
          "name": "Pizza",
          "created_at": "2024-07-13T12:07:46.781722Z",
          "subcategory": 16,
          "vendor": null
        },
        "menu_item": "Chicken Caesar Salad",
        "item_type": "Vegetarian",
        "description": "Classic Italian pizza topped with tomato sauce, mozzarella cheese, and fresh basil.",
        "price": "750.00",
        "s_price": null,
        "m_price": null,
        "l_price": null,
        "xl_price": null,
        "size_type": "nan",
        "estimate_time": 25,
        "spiciness": "Medium",
        "calories": "250.00",
        "stock": 20,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.50",
        "created_at": "2024-07-13T12:37:03Z",
        "vendor": 30
      },
      {
        "id": 258,
        "ingredients": [
          "[",
          "'",
          "F",
          "l",
          "o",
          "u",
          "r",
          "'",
          ",",
          " ",
          "'",
          "T",
          "o",
          "m",
          "a",
          "t",
          "o",
          " ",
          "s",
          "a",
          "u",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "M",
          "o",
          "z",
          "z",
          "a",
          "r",
          "e",
          "l",
          "l",
          "a",
          " ",
          "c",
          "h",
          "e",
          "e",
          "s",
          "e",
          "'",
          ",",
          " ",
          "'",
          "B",
          "a",
          "s",
          "i",
          "l",
          "'",
          "]"
        ],
        "category": {
          "id": 43,
          "name": "Food",
          "created_at": "2024-07-13T11:27:33.935956Z",
          "vendor": 32
        },
        "sub_category": {
          "id": 31,
          "name": "Main Course",
          "created_at": "2024-07-13T12:07:46.768169Z",
          "category": 22,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 23,
          "name": "Pizza",
          "created_at": "2024-07-13T12:07:46.781722Z",
          "subcategory": 16,
          "vendor": null
        },
        "menu_item": "Margherita Pizza",
        "item_type": "Vegetarian",
        "description": "Traditional Italian pizza topped with tomato sauce, mozzarella cheese, and fresh basil leaves.",
        "price": "800.00",
        "s_price": "0.00",
        "m_price": "0.00",
        "l_price": "0.00",
        "xl_price": "0.00",
        "size_type": "NA",
        "estimate_time": 30,
        "spiciness": "Medium",
        "calories": "300.00",
        "stock": 30,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.20",
        "created_at": "2024-07-13T12:37:03Z",
        "vendor": 30
      },
      {
        "id": 271,
        "ingredients": [
          "[",
          "'",
          "F",
          "l",
          "o",
          "u",
          "r",
          "'",
          ",",
          " ",
          "'",
          "T",
          "o",
          "m",
          "a",
          "t",
          "o",
          " ",
          "s",
          "a",
          "u",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "M",
          "o",
          "z",
          "z",
          "a",
          "r",
          "e",
          "l",
          "l",
          "a",
          " ",
          "c",
          "h",
          "e",
          "e",
          "s",
          "e",
          "'",
          ",",
          " ",
          "'",
          "B",
          "a",
          "s",
          "i",
          "l",
          "'",
          "]"
        ],
        "category": {
          "id": 44,
          "name": "Italian",
          "created_at": "2024-07-18T18:50:01.256690Z",
          "vendor": null
        },
        "sub_category": {
          "id": 32,
          "name": "nan",
          "created_at": "2024-07-18T18:50:01.313813Z",
          "category": 35,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 43,
          "name": "",
          "created_at": "2024-07-18T18:50:01.362076Z",
          "subcategory": 21,
          "vendor": null
        },
        "menu_item": "Vegetarian",
        "item_type": "Vegetarian",
        "description": "Traditional Italian pizza topped with tomato sauce, mozzarella cheese, and fresh basil leaves.",
        "price": null,
        "s_price": "0.00",
        "m_price": "0.00",
        "l_price": "0.00",
        "xl_price": "0.00",
        "size_type": "nan",
        "estimate_time": 30,
        "spiciness": "Medium",
        "calories": "300.00",
        "stock": 30,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.20",
        "created_at": "2024-07-18T18:50:01.430456Z",
        "vendor": 30
      },
      {
        "id": 272,
        "ingredients": [
          "[",
          "'",
          "C",
          "h",
          "i",
          "c",
          "k",
          "e",
          "n",
          " ",
          "b",
          "r",
          "e",
          "a",
          "s",
          "t",
          "'",
          ",",
          " ",
          "'",
          "Y",
          "o",
          "g",
          "u",
          "r",
          "t",
          "'",
          ",",
          " ",
          "'",
          "G",
          "i",
          "n",
          "g",
          "e",
          "r",
          "'",
          ",",
          " ",
          "'",
          "G",
          "a",
          "r",
          "l",
          "i",
          "c",
          "'",
          ",",
          " ",
          "'",
          "G",
          "a",
          "r",
          "a",
          "m",
          " ",
          "m",
          "a",
          "s",
          "a",
          "l",
          "a",
          "'",
          ",",
          " ",
          "'",
          "C",
          "u",
          "m",
          "i",
          "n",
          "'",
          ",",
          " ",
          "'",
          "P",
          "a",
          "p",
          "r",
          "i",
          "k",
          "a",
          "'",
          ",",
          " ",
          "'",
          "L",
          "e",
          "m",
          "o",
          "n",
          " ",
          "j",
          "u",
          "i",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "M",
          "i",
          "n",
          "t",
          " ",
          "c",
          "h",
          "u",
          "t",
          "n",
          "e",
          "y",
          "'",
          "]"
        ],
        "category": {
          "id": 36,
          "name": "Indian",
          "created_at": "2024-07-18T18:50:01.564592Z",
          "vendor": null
        },
        "sub_category": {
          "id": 22,
          "name": "nan",
          "created_at": "2024-07-18T18:50:01.606757Z",
          "category": 36,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 33,
          "name": "",
          "created_at": "2024-07-18T18:50:01.672557Z",
          "subcategory": 22,
          "vendor": null
        },
        "menu_item": "Non-Vegetarian",
        "item_type": "Non-Vegetarian",
        "description": "Grilled chicken marinated in a blend of Indian spices served with mint chutney.",
        "price": null,
        "s_price": "0.00",
        "m_price": "0.00",
        "l_price": "0.00",
        "xl_price": "0.00",
        "size_type": "nan",
        "estimate_time": 40,
        "spiciness": "Medium",
        "calories": "400.00",
        "stock": 25,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.60",
        "created_at": "2024-07-18T18:50:01.744567Z",
        "vendor": 30
      },
      {
        "id": 273,
        "ingredients": [
          "[",
          "'",
          "R",
          "o",
          "m",
          "a",
          "i",
          "n",
          "e",
          " ",
          "l",
          "e",
          "t",
          "t",
          "u",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "C",
          "r",
          "o",
          "u",
          "t",
          "o",
          "n",
          "s",
          "'",
          ",",
          " ",
          "'",
          "P",
          "a",
          "r",
          "m",
          "e",
          "s",
          "a",
          "n",
          " ",
          "c",
          "h",
          "e",
          "e",
          "s",
          "e",
          "'",
          ",",
          " ",
          "'",
          "C",
          "a",
          "e",
          "s",
          "a",
          "r",
          " ",
          "d",
          "r",
          "e",
          "s",
          "s",
          "i",
          "n",
          "g",
          "'",
          "]"
        ],
        "category": {
          "id": 24,
          "name": "Salad",
          "created_at": "2024-07-13T11:27:55.054329Z",
          "vendor": 32
        },
        "sub_category": {
          "id": 23,
          "name": "nan",
          "created_at": "2024-07-18T18:50:01.813599Z",
          "category": 24,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 34,
          "name": "",
          "created_at": "2024-07-18T18:50:02.009765Z",
          "subcategory": 23,
          "vendor": null
        },
        "menu_item": "Vegetarian",
        "item_type": "Vegetarian",
        "description": "Classic Caesar salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.",
        "price": null,
        "s_price": "0.00",
        "m_price": "0.00",
        "l_price": "0.00",
        "xl_price": "0.00",
        "size_type": "nan",
        "estimate_time": 20,
        "spiciness": "Medium",
        "calories": "200.00",
        "stock": 20,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.40",
        "created_at": "2024-07-18T18:50:02.073673Z",
        "vendor": 30
      },
      {
        "id": 274,
        "ingredients": [
          "[",
          "'",
          "R",
          "i",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "K",
          "i",
          "m",
          "c",
          "h",
          "i",
          "'",
          ",",
          " ",
          "'",
          "T",
          "o",
          "f",
          "u",
          "'",
          ",",
          " ",
          "'",
          "C",
          "a",
          "r",
          "r",
          "o",
          "t",
          "s",
          "'",
          ",",
          " ",
          "'",
          "G",
          "r",
          "e",
          "e",
          "n",
          " ",
          "o",
          "n",
          "i",
          "o",
          "n",
          "s",
          "'",
          ",",
          " ",
          "'",
          "G",
          "a",
          "r",
          "l",
          "i",
          "c",
          "'",
          ",",
          " ",
          "'",
          "S",
          "o",
          "y",
          " ",
          "s",
          "a",
          "u",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "S",
          "e",
          "s",
          "a",
          "m",
          "e",
          " ",
          "o",
          "i",
          "l",
          "'",
          ",",
          " ",
          "'",
          "R",
          "e",
          "d",
          " ",
          "p",
          "e",
          "p",
          "p",
          "e",
          "r",
          " ",
          "f",
          "l",
          "a",
          "k",
          "e",
          "s",
          "'",
          "]"
        ],
        "category": {
          "id": 37,
          "name": "Korean",
          "created_at": "2024-07-18T18:50:02.230601Z",
          "vendor": null
        },
        "sub_category": {
          "id": 24,
          "name": "nan",
          "created_at": "2024-07-18T18:50:02.284855Z",
          "category": 37,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 35,
          "name": "",
          "created_at": "2024-07-18T18:50:02.423624Z",
          "subcategory": 24,
          "vendor": null
        },
        "menu_item": "Vegetarian",
        "item_type": "Vegetarian",
        "description": "Spicy Korean fried rice with kimchi, vegetables, and tofu.",
        "price": null,
        "s_price": "0.00",
        "m_price": "0.00",
        "l_price": "0.00",
        "xl_price": "0.00",
        "size_type": "nan",
        "estimate_time": 35,
        "spiciness": "Medium",
        "calories": "350.00",
        "stock": 30,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.30",
        "created_at": "2024-07-18T18:50:02.522908Z",
        "vendor": 30
      },
      {
        "id": 275,
        "ingredients": [
          "[",
          "'",
          "C",
          "o",
          "d",
          " ",
          "f",
          "i",
          "l",
          "l",
          "e",
          "t",
          "s",
          "'",
          ",",
          " ",
          "'",
          "F",
          "l",
          "o",
          "u",
          "r",
          "'",
          ",",
          " ",
          "'",
          "B",
          "e",
          "e",
          "r",
          "'",
          ",",
          " ",
          "'",
          "B",
          "a",
          "k",
          "i",
          "n",
          "g",
          " ",
          "p",
          "o",
          "w",
          "d",
          "e",
          "r",
          "'",
          ",",
          " ",
          "'",
          "P",
          "o",
          "t",
          "a",
          "t",
          "o",
          "e",
          "s",
          "'",
          ",",
          " ",
          "'",
          "O",
          "i",
          "l",
          "'",
          ",",
          " ",
          "'",
          "S",
          "a",
          "l",
          "t",
          "'",
          ",",
          " ",
          "'",
          "P",
          "e",
          "p",
          "p",
          "e",
          "r",
          "'",
          ",",
          " ",
          "'",
          "L",
          "e",
          "m",
          "o",
          "n",
          " ",
          "w",
          "e",
          "d",
          "g",
          "e",
          "s",
          "'",
          ",",
          " ",
          "'",
          "T",
          "a",
          "r",
          "t",
          "a",
          "r",
          " ",
          "s",
          "a",
          "u",
          "c",
          "e",
          "'",
          "]"
        ],
        "category": {
          "id": 38,
          "name": "Seafood",
          "created_at": "2024-07-18T18:50:02.575333Z",
          "vendor": null
        },
        "sub_category": {
          "id": 25,
          "name": "Available",
          "created_at": "2024-07-18T18:50:02.631775Z",
          "category": 38,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 36,
          "name": "",
          "created_at": "2024-07-18T18:50:02.727668Z",
          "subcategory": 25,
          "vendor": null
        },
        "menu_item": "Non-Vegetarian",
        "item_type": "Non-Vegetarian",
        "description": "Classic British dish featuring battered and deep-fried fish served with crispy fries and tartar sauce.",
        "price": null,
        "s_price": "200.00",
        "m_price": "300.00",
        "l_price": "400.00",
        "xl_price": "0.00",
        "size_type": "Available",
        "estimate_time": 45,
        "spiciness": "Medium",
        "calories": "500.00",
        "stock": 15,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.70",
        "created_at": "2024-07-18T18:50:02.791123Z",
        "vendor": 30
      },
      {
        "id": 276,
        "ingredients": [
          "[",
          "'",
          "P",
          "a",
          "n",
          "e",
          "e",
          "r",
          "'",
          ",",
          " ",
          "'",
          "T",
          "o",
          "m",
          "a",
          "t",
          "o",
          "e",
          "s",
          "'",
          ",",
          " ",
          "'",
          "O",
          "n",
          "i",
          "o",
          "n",
          "s",
          "'",
          ",",
          " ",
          "'",
          "Y",
          "o",
          "g",
          "u",
          "r",
          "t",
          "'",
          ",",
          " ",
          "'",
          "C",
          "r",
          "e",
          "a",
          "m",
          "'",
          ",",
          " ",
          "'",
          "G",
          "i",
          "n",
          "g",
          "e",
          "r",
          "'",
          ",",
          " ",
          "'",
          "G",
          "a",
          "r",
          "l",
          "i",
          "c",
          "'",
          ",",
          " ",
          "'",
          "G",
          "a",
          "r",
          "a",
          "m",
          " ",
          "m",
          "a",
          "s",
          "a",
          "l",
          "a",
          "'",
          ",",
          " ",
          "'",
          "C",
          "o",
          "r",
          "i",
          "a",
          "n",
          "d",
          "e",
          "r",
          " ",
          "p",
          "o",
          "w",
          "d",
          "e",
          "r",
          "'",
          ",",
          " ",
          "'",
          "C",
          "u",
          "m",
          "i",
          "n",
          " ",
          "p",
          "o",
          "w",
          "d",
          "e",
          "r",
          "'",
          ",",
          " ",
          "'",
          "N",
          "a",
          "a",
          "n",
          " ",
          "b",
          "r",
          "e",
          "a",
          "d",
          "'",
          "]"
        ],
        "category": {
          "id": 36,
          "name": "Indian",
          "created_at": "2024-07-18T18:50:01.564592Z",
          "vendor": null
        },
        "sub_category": {
          "id": 26,
          "name": "Available",
          "created_at": "2024-07-18T18:50:02.859709Z",
          "category": 36,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 37,
          "name": "",
          "created_at": "2024-07-18T18:50:02.897483Z",
          "subcategory": 26,
          "vendor": null
        },
        "menu_item": "Vegetarian",
        "item_type": "Vegetarian",
        "description": "Cottage cheese cubes cooked in a creamy tomato-based sauce with Indian spices, served with naan bread.",
        "price": null,
        "s_price": "400.00",
        "m_price": "450.00",
        "l_price": "500.00",
        "xl_price": "650.00",
        "size_type": "Available",
        "estimate_time": 40,
        "spiciness": "Medium",
        "calories": "450.00",
        "stock": 25,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.50",
        "created_at": "2024-07-18T18:50:02.962806Z",
        "vendor": 30
      },
      {
        "id": 277,
        "ingredients": [
          "[",
          "'",
          "L",
          "i",
          "m",
          "e",
          " ",
          "j",
          "u",
          "i",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "S",
          "i",
          "m",
          "p",
          "l",
          "e",
          " ",
          "s",
          "y",
          "r",
          "u",
          "p",
          "'",
          ",",
          " ",
          "'",
          "C",
          "l",
          "u",
          "b",
          " ",
          "s",
          "o",
          "d",
          "a",
          "'",
          ",",
          " ",
          "'",
          "S",
          "a",
          "l",
          "t",
          "'",
          "]"
        ],
        "category": {
          "id": 39,
          "name": "Cocktail",
          "created_at": "2024-07-18T18:50:03.007704Z",
          "vendor": null
        },
        "sub_category": {
          "id": 27,
          "name": "Available",
          "created_at": "2024-07-18T18:50:03.048134Z",
          "category": 39,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 38,
          "name": "",
          "created_at": "2024-07-18T18:50:03.093890Z",
          "subcategory": 27,
          "vendor": null
        },
        "menu_item": "Non-Alcoholic",
        "item_type": "Non-Alcoholic",
        "description": "Refreshing blend of lime juice, simple syrup, and club soda served in a salt-rimmed glass.",
        "price": null,
        "s_price": "500.00",
        "m_price": "600.00",
        "l_price": "0.00",
        "xl_price": "0.00",
        "size_type": "Available",
        "estimate_time": 15,
        "spiciness": "Medium",
        "calories": "150.00",
        "stock": 20,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.80",
        "created_at": "2024-07-18T18:50:03.145004Z",
        "vendor": 30
      },
      {
        "id": 278,
        "ingredients": [
          "[",
          "'",
          "L",
          "i",
          "m",
          "e",
          " ",
          "j",
          "u",
          "i",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "M",
          "i",
          "n",
          "t",
          " ",
          "l",
          "e",
          "a",
          "v",
          "e",
          "s",
          "'",
          ",",
          " ",
          "'",
          "S",
          "u",
          "g",
          "a",
          "r",
          "'",
          ",",
          " ",
          "'",
          "S",
          "o",
          "d",
          "a",
          " ",
          "w",
          "a",
          "t",
          "e",
          "r",
          "'",
          "]"
        ],
        "category": {
          "id": 40,
          "name": "Mocktail",
          "created_at": "2024-07-18T18:50:03.192836Z",
          "vendor": null
        },
        "sub_category": {
          "id": 28,
          "name": "Available",
          "created_at": "2024-07-18T18:50:03.231050Z",
          "category": 40,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 39,
          "name": "",
          "created_at": "2024-07-18T18:50:03.270744Z",
          "subcategory": 28,
          "vendor": null
        },
        "menu_item": "Non-Alcoholic",
        "item_type": "Non-Alcoholic",
        "description": "A mocktail version of the classic mojito made with lime juice, mint leaves, sugar, and soda water.",
        "price": null,
        "s_price": "600.00",
        "m_price": "690.00",
        "l_price": "0.00",
        "xl_price": "0.00",
        "size_type": "Available",
        "estimate_time": 10,
        "spiciness": "Medium",
        "calories": "120.00",
        "stock": 25,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.60",
        "created_at": "2024-07-18T18:50:03.316675Z",
        "vendor": 30
      },
      {
        "id": 279,
        "ingredients": [
          "[",
          "'",
          "F",
          "l",
          "o",
          "u",
          "r",
          "'",
          ",",
          " ",
          "'",
          "T",
          "o",
          "m",
          "a",
          "t",
          "o",
          " ",
          "s",
          "a",
          "u",
          "c",
          "e",
          "'",
          ",",
          " ",
          "'",
          "M",
          "o",
          "z",
          "z",
          "a",
          "r",
          "e",
          "l",
          "l",
          "a",
          " ",
          "c",
          "h",
          "e",
          "e",
          "s",
          "e",
          "'",
          ",",
          " ",
          "'",
          "P",
          "e",
          "p",
          "p",
          "e",
          "r",
          "o",
          "n",
          "i",
          "'",
          "]"
        ],
        "category": {
          "id": 35,
          "name": "Italian",
          "created_at": "2024-07-18T18:50:01.256690Z",
          "vendor": null
        },
        "sub_category": {
          "id": 29,
          "name": "Available",
          "created_at": "2024-07-18T18:50:03.377924Z",
          "category": 35,
          "vendor": null
        },
        "sub_sub_category": {
          "id": 40,
          "name": "",
          "created_at": "2024-07-18T18:50:03.424926Z",
          "subcategory": 29,
          "vendor": null
        },
        "menu_item": "Non-Vegetarian",
        "item_type": "Non-Vegetarian",
        "description": "Classic pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
        "price": null,
        "s_price": "700.00",
        "m_price": "900.00",
        "l_price": "0.00",
        "xl_price": "0.00",
        "size_type": "Available",
        "estimate_time": 35,
        "spiciness": "Medium",
        "calories": "400.00",
        "stock": 15,
        "in_stock": true,
        "chef_special": true,
        "upcoming": true,
        "rating": "4.40",
        "created_at": "2024-07-18T18:50:03.481413Z",
        "vendor": 30
      }
    ]
  };
  new_obj: any;

  categoriesList: any;
  subcategoriesList: any;
  subSubcategoriesList: any;


  constructor(private inventoryService: InventoryService) {

  }

  ngOnInit(): void {
    this.getCategroiesList();
    this.getSubCategoriesList();
    this.getSubSubCategoriesList();
    console.log('Devesh', this.obj);




    const groupedItems = this.obj.response.reduce((acc: any, item: any) => {
      const categoryName = item.category.id;
      const subCategoryName = item.sub_category.id;
      const subSubCategoryName = item.sub_sub_category.id;

      if (!acc[categoryName]) {
        acc[categoryName] = {};
      }
      if (!acc[categoryName][subCategoryName]) {
        acc[categoryName][subCategoryName] = {};
      }
      if (!acc[categoryName][subCategoryName][subSubCategoryName]) {
        acc[categoryName][subCategoryName][subSubCategoryName] = [];
      }
      acc[categoryName][subCategoryName][subSubCategoryName].push(item);
      return acc;
    }, {})


    this.new_obj = groupedItems;
    console.log('this.new_obj: ', this.new_obj);



    // let myData = this.transformMenuData(this.new_obj);
    // console.log('myData: ', myData);





  }


  getCategroiesList() {
    this.inventoryService.getCategories().subscribe((res: any) => {
      // console.log('this.categoriesList: ', res);


      this.categoriesList = res.response;
      // console.log('this.categoriesList: ', this.categoriesList);
    })

  }

  getSubCategoriesList() {
    this.inventoryService.getSubCategories().subscribe((res: any) => {
      this.subcategoriesList = res.response;
      // console.log('this.subcategoriesList: ', this.subcategoriesList);

    })
  }

  getSubSubCategoriesList() {
    this.inventoryService.getSubSubCategories().subscribe((res: any) => {
      this.subSubcategoriesList = res.response;
      console.log('this.subSubcategoriesList: ', this.subSubcategoriesList);

    })
  }


  getCategoryName(item: any) {
    if (this.categoriesList)
      for (let elem of this.categoriesList) {
        // console.log('=======', elem);
        if (elem.id == item) {
          return elem.name

        }

      }


    return 'Devesh';
  }

  getSubCategoryName(item: any) {
    if (this.subcategoriesList)
      for (let elem of this.subcategoriesList) {
        // console.log('------- ', elem);
        if (elem.id == item)
          return elem.name

      }
    return 'Bhatia'

  }



  getSubSubCategoryName(item: any) {
    if (this.subSubcategoriesList)
      for (let elem of this.subSubcategoriesList) {
        // console.log('------- ', elem);
        if (elem.id == item)
          return elem.name

      }
    return 'Bhatias'
  }



  transformMenuData(data: any): any[] {
    const result = [];
    for (const catKey in data) {
      if (data.hasOwnProperty(catKey)) {
        for (const subCatKey in data[catKey]) {
          if (data[catKey].hasOwnProperty(subCatKey)) {
            for (const subSubCatKey in data[catKey][subCatKey]) {
              if (data[catKey][subCatKey].hasOwnProperty(subSubCatKey)) {
                result.push({
                  category: catKey,
                  subCategory: subCatKey,
                  subSubCategory: subSubCatKey,
                  items: data[catKey][subCatKey][subSubCatKey]
                });
              }
            }
          }
        }
      }
    }
    return result;
  }




}
